version: '3'
services:
  webserver:
    build: .
    container_name: webserver
    ports:
      - '8080:80' # Puerto HTTP
      - '8443:443' # Puerto HTTPS
    volumes:
      - ./web:/usr/local/apache2/htdocs/
      - ./server.crt:/usr/local/apache2/conf/server.crt
      - ./server.key:/usr/local/apache2/conf/server.key

  ftpserver:
    build:
      context: .
      dockerfile: Dockerfile.ftp
    container_name: ftpserver
    ports:
      - '21:21' # Puerto FTP
      - '30000-30009:30000-30009' # Puertos pasivos FTPS
    environment:
      FTP_USER_NAME: 'test'
      FTP_USER_PASS: 'test123'
      FTP_USER_HOME: '/home/test'
      FTP_PASSIVE_PORTS: '30000:30009'
      ADDED_FLAGS: '--tls=2' # TLS obligatorio
    volumes:
      - ./ftp:/home/test
      - ./pure-ftpd.pem:/etc/ssl/private/pure-ftpd.pem # Montar el archivo PEM para FTPS

networks:
  default:
    driver: bridge
